/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ctwl_lzq_howmuchanimation_Utils_UpdataUtils */

#ifndef _Included_com_ctwl_lzq_howmuchanimation_Utils_UpdataUtils
#define _Included_com_ctwl_lzq_howmuchanimation_Utils_UpdataUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ctwl_lzq_howmuchanimation_Utils_UpdataUtils
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ctwl_lzq_howmuchanimation_Utils_UpdataUtils_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
